import Head from 'next/head';
import { BiUserPlus, BiX, BiCheck } from 'react-icons/bi';
import Table from '../components/table';
import Form from '../components/form';
import { useState } from 'react';
import { useSelector, useDispatch } from 'react-redux';
import { toggleChangeAction, deleteAction } from '../redux/reducer';
import { deleteUser, getUsers } from '../lib/helper';
import { useQueryClient } from 'react-query';

export default function Home() {
  // const [visible, setVisible] = useState(false);
  const visible = useSelector((state) => state.app.client.toggleForm);
  const deleteId = useSelector((state) => state.app.client.deleteId);
  const queryclient = useQueryClient();
  const dispatch = useDispatch();
  const handleAddForm = () => {
    // setVisible(!visible);
    dispatch(toggleChangeAction());
  };
  const deletehandler = async () => {
    if (deleteId) {
      await deleteUser(deleteId);
      await queryclient.prefetchQuery('users', getUsers);
      await dispatch(deleteAction(null));
    }
  };

  const canclehandler = async () => {
    console.log('cancel');
    await dispatch(deleteAction(null));
  };
  return (
    <section>
      <Head>
        <title>CRUD Sederhana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl md:text-5xl text-center font-bold py-10"> Employeee Project</h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button
              onClick={handleAddForm}
              className="flex bg-indigo-500 text-white px-4 py-2 border rounded-md hover:bg-gray-50 hover:border-indigo-500 hover:text-gray-800"
            >
              Add Employee{' '}
              <span className="px-1">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>
          {deleteId ? DeleteComponent({ deletehandler, canclehandler }) : <></>}

          {/* collapseable from */}
          {/* <div className="right flex gap-3">
            <button className="flex bg-indigo-500 text-white px-4 rounded-md hover:bg-gray-50 hover:text-indigo-500 hover:border-indigo-500">
              <BiUserPlus className="w-6 h-6"></BiUserPlus>
            </button>
          </div> */}
        </div>
        {/* Collapse Table */}
        {visible ? <Form></Form> : <></>}
        {/* Table */}
        <div className="container mx-auto">
          <Table></Table>
        </div>
      </main>
    </section>
  );
}
function DeleteComponent({ deletehandler, canclehandler }) {
  return (
    <div className="flex gap-5">
      <button>Are you sure?</button>
      <button
        onClick={deletehandler}
        className="flex bg-red-500 text-white px-4 py-2 border rounded-md hover:bg-rose-500 hover:border-red-500 hover:text-gray-50"
      >
        Yes{' '}
        <span className="px-1">
          <BiX color="rgb(255 255 255)" size={25} />
        </span>
      </button>
      <button
        onClick={canclehandler}
        className="flex bg-green-500 text-white px-4 py-2 border rounded-md hover:bg-gree-500 hover:border-green-500 hover:text-gray-50"
      >
        No{' '}
        <span className="px-1">
          <BiCheck color="rgb(255 255 255)" size={25} />
        </span>
      </button>
    </div>
  );
}
