import Head from 'next/head';
import { BiUserPlus } from 'react-icons/bi';

export default function Home() {
  return (
    <section>
      <Head>
        <title>CRUD Sederhana</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1 className="text-xl md:text-5xl text-center font-bold py-10"> Employeee Project</h1>
        <div className="container mx-auto flex justify-between py-5 border-b">
          <div className="left flex gap-3">
            <button className="flex bg-indigo-500 text-white px-4 rounded-md hover:bg-gray-50 hover:text-indigo-500 hover:border-indigo-500">
              Employee{' '}
              <span className="px-1">
                <BiUserPlus size={23}></BiUserPlus>
              </span>
            </button>
          </div>

          {/* collapseable from */}
          {/* <div className="right flex gap-3">
            <button className="flex bg-indigo-500 text-white px-4 rounded-md hover:bg-gray-50 hover:text-indigo-500 hover:border-indigo-500">
              <BiUserPlus className="w-6 h-6"></BiUserPlus>
            </button>
          </div> */}
        </div>
      </main>
    </section>
  );
}
